# Generated by Django 5.2.8 on 2025-12-31 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('SYSTEM', 'System Alert'), ('FILE', 'File')], default='TEXT', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='django_backend.meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='chat_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting', to='django_backend.chatroom'),
        ),
    ]
