# Generated by Django 5.2.8 on 2026-01-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0002_chatmessage_message_type_event_meeting_and_more'),
        ('django_backend', '0002_user_otp_user_otp_expires_at'),
    ]

    operations = [
    ]
